### ISSUE TITLE
How to cancel following

### ISSUE THREAD

**Issue by yaochiqkl** [popsiclesarecool/followproject#2]
I mean , after following so many people .
Once regret , it there a method to unfollow them ?

**Comment by popsiclesarecool** [comment]
You can modify the script. Then point the script at yourself to unfollow everyone. Something like this... might or might not work

## Arguments
```
casperjs follow2.js yourusername yourpassword test.json
```

test.json
```javascript
["yourusername"]
```

## follow2.js Modifications

replace
https://github.com/popsiclesarecool/followproject/blob/master/follow2.js#L122
with
```javascript
if (isfollow !== -1)
```

<br><br>
<br><br>

replace
https://github.com/popsiclesarecool/followproject/blob/master/follow2.js#L148
with
```javascript
//pagenum++;
```

<br><br>
<br><br>

replace
https://github.com/popsiclesarecool/followproject/blob/master/follow2.js#L169-L170
with
```javascript
casper.echo("https://github.com/"+target+"/following?page="+pagenum.toString());
casper.thenOpen(("https://github.com/"+target+"/following?page="+pagenum.toString()) , evalfollow);
```

**Comment by yaochiqkl** [comment]
Thanks very much :smile:
